five-star-school/eduWithMe-frontend

src/App.js, src/pages/RoomPage.jsx, src/styles/RoomPage.module.css
> #5
> Close #5 
> - RoomPage 생성
> - 라우터 세팅
> 잘 작동하나 확인해주세요
=> [#5] ✨ feat : RoomPage 구현

src/App.js, src/components/HeaderNavComponent.jsx, src/components/MainContentComponent.jsx, src/components/SidebarComponent.jsx, src/pages/RoomPage.jsx, src/styles/HeaderNavComponent.module.css, src/styles/MainContentComponent.module.css, src/styles/RoomPage.module.css, src/styles/SidebarComponent.module.css
> #9 
> Close #9 
> - Sidebar (왼쪽 사이드바) 구현
> - HeaderNav (상단 네비게이션 바) 구현
> - MainContent (메인 콘텐츠 영역) 구현
>
=> [#9] 🩹 fix : RoomPage Components 구역 구현 및 스타일 수정

src/components/RoomLayout.jsx, src/pages/RoomPage.jsx, src/styles/RoomLayout.module.css, src/styles/SidebarComponent.module.css
> #15
> Close #15
> - RoomLayout 구현
>
=> [#15] ✨feat : RoomLayout 구현

src/components/SpaceCard.jsx, src/styles/SpaceCard.module.css
> #11
> Close #11
> - ![image](https://github.com/user-attachments/assets/a657bcdc-a639-4fbb-8a28-689fac2fbb72)
> - 방 생성 모달창 구현
>
=> [#11] ✨feat : 방 생성 모달창 구현

package-lock.json, package.json, src/App.js, src/components/Login.jsx, src/pages/LoginPage.jsx, src/styles/Login.module.css
> #7
> Close #7
> - (스크린샷 선택)
>
=> [#7] ✨ 로그인 페이지 구현

src/components/SpaceCard.jsx
> #23
> Close #23
> - ![image](https://github.com/user-attachments/assets/904abc04-a506-4752-b3d7-a8a52aff31d6)
> - 방 생성 시 방 추가 구현
>
=> [#23] ✨feat : 방 생성 시 방 추가 구현

src/App.js, src/components/Header.jsx, src/components/Login.jsx, src/components/Signup.jsx, src/pages/SignupPage.jsx, src/styles/Signup.module.css
> #20
> Close #20
> - (스크린샷 선택)
>
=> [#20] ✨ feat : 회원가입 페이지 구현

package-lock.json, src/App.js, src/pages/QuestionDetailPage.jsx, src/styles/QuestionDetailPage.module.css
> #14
> Close #14 
> -  QuestionDetailPage 구현
> -
>
=> [#14] ✨feat : QuestionDetailPage 구현

src/components/SpaceCard.jsx, src/styles/SpaceCard.module.css
> #27
> Close #27
> -  방 생성 모달 기능 수정
> - 방 생성 시 비밀번호 모달 비밀번호 초기화
> - 방 생성 시 private인 경우 비밀번호 필수 입력
> - private, public 버튼 호버 스타일 추가
>
=> [#27] ✨fix : 방 생성 모달 기능 수정

src/App.js, src/components/ChangePassword.jsx, src/pages/ChangePasswordPage.jsx, src/styles/ChangePassword.module.css
> #26
> Close #26
> ![image](https://github.com/user-attachments/assets/b92458f8-b0f3-4c3e-8428-dd299a57f895)
> - 예외처리 alert 창 띄우기
>
=> [#26] ✨ feat : 비밀번호 수정 페이지 구현

.idea/.gitignore, .idea/eduWithMe-frontend.iml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, package-lock.json, src/App.js, src/components/ManageMainHeaderNav.jsx, src/pages/ManageMainPage.jsx, src/styles/ManageMainHeaderNav.module.css, src/styles/ManageMainPage.module.css
> #21 
> Close #21 
> - 
> -관리자 메인 페이지 구현
>
=> [#21] ✨ feat : 관리자 메인 페이지 구현

package-lock.json, src/App.js, src/components/ChangePassword.jsx, src/components/ForgotPassword.jsx, src/components/Login.jsx, src/components/Signup.jsx, src/pages/ChangePasswordPage.jsx, src/pages/ForgotPasswordPage.jsx, src/styles/ChangePassword.module.css, src/styles/ForgotPassword.module.css
> #37
> Close #37
> - (스크린샷 선택)
> - 이메일 예외처리 구현
>
=> [#37] ✨ feat : 비밀번호 찾기 페이지 구현

src/App.js, src/components/ManageCreateHeaderNav.jsx, src/pages/ManageCreatePage.jsx, src/styles/ManageCreateHeaderNav.module.css, src/styles/ManageCreatePage.module.css
> #39 
> Close #39 
> - ![image](https://github.com/user-attachments/assets/b1e71e3e-7004-4087-b242-4a53ca9dc9ea)
> - 관리자 문제 생성 페이지 구현
>
=> [#39] ✨ feat : 관리자 문제 생성 페이지 구현

src/components/ChatWidget.jsx, src/components/RoomLayout.jsx, src/styles/ChatWidget.module.css
> #32 
> Close #32
> - ![image](https://github.com/user-attachments/assets/d9717a77-e9a2-427b-b409-44a78789a1c6)
> - 실시간 채팅 리모컨 기능 구현
>
=> [#32] ✨feat : 실시간 채팅 리모컨 기능 구현

src/App.js, src/components/MyComments.jsx, src/components/SolvedProblems.jsx, src/components/UserInfo.jsx, src/components/WrongAnswers.jsx, src/pages/MyPage.jsx, src/styles/MyComments.module.css, src/styles/MyPage.module.css, src/styles/SolvedProblems.module.css, src/styles/UserInfo.module.css, src/styles/WrongAnswers.module.css
> #38 
> Close #38 
> - 마이페이지 구현
> -
>
=> [#38] ✨ feat : MyPage 구현

src/App.js, src/components/ManageReadSidebar.jsx, src/pages/ManageReadPage.jsx, src/styles/ManageReadPage.module.css, src/styles/ManageReadSidebar.module.css
> #43 
> Close #43
> - ![image](https://github.com/user-attachments/assets/16b2f828-51a7-425b-9c5f-64c710a17f03)
> - 관리자 문제 상세 페이지 구현
>
=> [#43] ✨ feat : 관리자 문제 상세 페이지 구현

src/App.js, src/pages/ManageModifyPage.jsx, src/styles/ManageModifyPage.module.css
> #52 
> Close #52 
> - ![image](https://github.com/user-attachments/assets/e8f9b7f9-a8ab-4751-ba25-aba15fc16dd4)
> - 관리자 문제 수정 페이지 구현
>
=> [#52] ✨ feat : 관리자 문제 수정 페이지 구현

package-lock.json, package.json, src/components/Login.jsx
> #58
> Close #58
> - login.jsx 백엔드 api 연동
>
=> [#58] ✨feat : login.jsx 백엔드 api 연동

src/components/Login.jsx
> #49
> Close #49 
> 로그인 성공 시 메인페이지로 이동
> ![image](https://github.com/user-attachments/assets/233251ef-159d-4f78-b1f2-a22d648c14b4)
> ![image](https://github.com/user-attachments/assets/3bb6bcb9-64d5-4cbb-8d34-25bd250c87a1)
>![image](https://github.com/user-attachments/assets/655c86ab-f118-4311-a1dc-4ea250f3f501)
>![image](https://github.com/user-attachments/assets/409c7bb6-e68b-4825-988d-963056471e05)
>
=> [#49] 🎉 add : Login 성공 시 main 페이지로 이동

src/components/SpaceCard.jsx
> #61
> Close #61
> - ![image](https://github.com/user-attachments/assets/b3fbda06-58f7-40fe-ab7d-16b6f4cd8932)
> - 방 조회 api 기능 구현
>
=> [#61] ✨feat : 방 조회 api 기능 구현

src/components/Signup.jsx
> #60 
> Close #60 
> - 회원가입 백엔드 연결
>
=> [#60] ✨ feat : 회원가입 백엔드 연결

src/components/SpaceCard.jsx, src/util/axiosConfig.js, src/util/cookie.js
> #이슈번호
> Close #이슈번호
> - ![image](https://github.com/user-attachments/assets/2c303693-28f2-4ea8-8308-affd9c6807a7)
> - 방 생성 기능 api 연결 구현
>
=> [#66] ✨feat : 방 생성 기능 api 연결 구현

src/components/MyPage/WrongAnswers.jsx, src/pages/MyPage.jsx
> #75
> Close #75
> - (스크린샷 선택) 해결한 문제 조회 페이지랑 일치
> - 오답 문제 조회
> - 페이징 처리
>
=> [#75] ✨ feat : 마이페이지 오답 문제 조회

src/components/MyPage/WrongAnswers.jsx
> #82
> Close #82
> - (스크린샷 선택)
>
=> [#82] 🩹 fix : 오답 문제 조회 때 questionId 사용으로 수정

src/components/QuestionDetail.jsx, src/components/RoomMain.jsx, src/styles/QuestionDetail.module.css
> #79 
> Close #79 
> ![image](https://github.com/user-attachments/assets/b73c93aa-52eb-43bd-98e1-5181e4d406de)
>
=> [#79] ✨ feat : RoomMainPage에서 문제 클릭후 QestionDestail 상세문제 api 연동

src/components/SidebarComponent.jsx, src/components/SpaceCard.jsx
> #74
> Close #74
> - ![image](https://github.com/user-attachments/assets/15b3b0e9-36f4-456c-a849-59a25fed45d0)
> - 방 입장 기능 api 연결 구현
>
=> [#74] ✨feat : 방 입장 기능 api 연결 구현

src/components/MyPage/SolvedProblems.jsx, src/components/MyPage/WrongAnswers.jsx
=> [#85] 🩹 fix  : 해결한문제, 오답문제 카테고리란 추가

src/components/HeaderNavComponent.jsx, src/components/RoomMain.jsx
> #88
> Close #88
> ![image](https://github.com/user-attachments/assets/dc4df9cf-f2b8-4e41-b90a-d94c3d1cd994)
> ![image](https://github.com/user-attachments/assets/c6392083-29e6-4f49-a5ad-d61785785c1e)
>
=> [#88] ✨ feat : 문제목록 버튼 api 연동, 검색 기능 api 연동

package-lock.json, package.json, public/index.html, src/components/Login.jsx
> #70 
> Close #70 
> - 카카오 로그인 API 연동
>
=> [#70] ✨ feat : 카카오 로그인 API 연동

src/components/Header.jsx, src/styles/ChatWidget.module.css, src/util/AuthContext.js
> #97
> Close #97
> - ![image](https://github.com/user-attachments/assets/13ae702f-5ccd-4e51-9a1e-c17b6d28d4eb)
> - 로그인 헤더 수정
>
=> [#97] 🩹fix : 로그인 헤더 수정

package-lock.json, package.json, src/components/ChatWidget.jsx, src/components/SpaceCard.jsx
> #109
> Close #109
> - ![image](https://github.com/user-attachments/assets/e13d03e9-cad3-486f-9500-14a3083c869d)
> - 채팅 api 연결 기능 구현
>
=> [#109] ✨feat : 채팅 api 연결 기능 구현

src/components/MyPage/UserInfo.jsx, src/pages/MyPage.jsx, src/styles/UserInfo.module.css, src/util/AuthContext.js
> #103
> Close #103
> - ![image](https://github.com/user-attachments/assets/1c1c0fa3-a30e-44ed-80c4-61679ce8208f)
> - ![image](https://github.com/user-attachments/assets/0518210f-2274-4724-887c-e50cb51cbddc)
>
=> [#103] ✨ 프로필 닉네임 수정 api 연동

src/components/MyPage/MyComments.jsx, src/components/MyPage/SolvedAnswers.jsx, src/components/MyPage/UserInfo.jsx, src/components/MyPage/WrongAnswers.jsx, src/pages/MyPage.jsx, src/styles/UserInfo.module.css, src/util/AuthContext.js
> #107
> Close #107
> - (스크린샷 선택)
> - 잘 조회됩니다.
>
=> [#107] 🩹 fix : 문제 조회 변수명 No -> Id로 변경

src/components/Manage/QuestionTable.jsx, src/pages/ManageMainPage.jsx, src/styles/ManageMainPage.module.css
> #116
> Close #116
> ![image](https://github.com/user-attachments/assets/2444d5a6-51ee-4fb0-80c4-e0928fb06d65)
>
=> [#116] 🩹 fix : 관리자 메인페이지 문제 컴포넌트 분리

src/components/CommentSection.jsx, src/styles/QuestionDetail.module.css
> #118 
> Close #118 
> - Comment 정렬코드 수정
> -  댓글 등록 위치 css 수정
>
=> [#118] 🩹 fix : Comment 정렬코드 수정 및 댓글 등록 위치 css 수정

src/components/QuestionDetail.jsx
> #121 
> Close #121 
> - ![image](https://github.com/user-attachments/assets/f1a11b2a-63d6-4703-9d47-876256d7c866)
> - ![image](https://github.com/user-attachments/assets/20805579-0bf7-4112-a0f9-b3fcb94a2684)
>
=> [#121] 🩹 fix : 문제 정답 제출 모달창 수정

src/components/Manage/QuestionDetail.jsx, src/components/Manage/QuestionSettings.jsx, src/pages/ManageCreatePage.jsx, src/styles/ManageCreatePage.module.css, src/styles/QuestionDetail.module.css
> #119
> Close #119
> - (스크린샷 선택)
> - Detail, Settings 분리
>
=> [#119] 🩹 fix : 관리자 생성페이지 컴포넌트 분리

src/App.js, src/components/HeaderNavComponent.jsx
> #126
> Close #126
> - ![image](https://github.com/user-attachments/assets/68a30e43-195c-4c37-8750-23bfe520f25b)
> - 관리자 페이지 사이드바 수정 구현
>
=> [#126] 🩹fix : 관리자 페이지 사이드바 수정 구현

src/App.js, src/components/Manage/QuestionTable.jsx, src/pages/ManageMainPage.jsx, src/pages/QuestionUpdatePage.jsx
> #129
> Close #129
> - ![image](https://github.com/user-attachments/assets/3baa381d-123c-45c0-978d-31b2dfcb2084)
> - 관리자 메인 페이지 api 연결 기능 구현
>
=> [#129] ✨feat : 관리자 메인 페이지 api 연결 기능 구현

src/pages/ManageMainPage.jsx
> #132
> Close #132
> - (스크린샷 선택)
> - 관리자 메인 페이지 수정
>
=> [#132] 🩹fix : 관리자 메인 페이지 수정

src/pages/ManageReadPage.jsx
> #135 
> Close #135 
> - ![image](https://github.com/user-attachments/assets/cd4bbc53-c989-459c-819c-35ca6648b5a2)
> - 관리자 문제 상세 페이지 문제 조회 연결
>
=> [#135] ✨ feat : 관리자 문제 상세 페이지 문제 조회 연결 및 삭제

src/components/ManageMainHeaderNav.jsx, src/pages/ManageMainPage.jsx
> #134
> Close #134
> - ![image](https://github.com/user-attachments/assets/a9a8e6f8-4791-43d3-86b6-bfa3beb7411b)
> - 관리자 페이지 방 삭제 api 연결 기능 구현
>
=> [#134] ✨feat : 관리자 페이지 방 삭제 api 연결 기능 구현

src/components/MyPage/MyComments.jsx, src/components/MyPage/SolvedAnswers.jsx, src/components/MyPage/UserInfo.jsx, src/components/MyPage/WrongAnswers.jsx, src/pages/MyPage.jsx
> #124 
> Close #124 
> - comment 방이름 테이블 추가 //  프로필 수정 -> 닉네임 수정으로 변경
>![image](https://github.com/user-attachments/assets/e155e482-9269-402d-bffd-29caf9903933)
> ![image](https://github.com/user-attachments/assets/2f55a211-57dd-4ca4-8693-ca1c5029c263)
> ![image](https://github.com/user-attachments/assets/d1b47bd3-d0be-4c31-ba41-07355c2553a9)
> ![image](https://github.com/user-attachments/assets/18a2c53c-65c2-433e-80ff-fb5238eb92b6)
>
=> [#124] ✨feat : 마이페이지 roomName 테이블 추가 및 api 연동

src/App.js, src/pages/ManageModifyPage.jsx
> #139 
> Close #139 
> - 관리자 문제 수정 기능 API 연동
>
=> [#139] ✨ feat : 관리자 문제 수정 기능 API 연동

src/components/SpaceCard.jsx
> #144
> Close #144
> - ![image](https://github.com/user-attachments/assets/985b3bd2-f906-4d1d-ae14-cf582e5fd150)
> - 방 전체 조회 수정
>
=> [#144] 🩹fix : 방 전체 조회 수정

src/components/CommentSection.jsx, src/styles/QuestionDetail.module.css
> #140 
> Close #140 
> - comment 해당 작성자만 수정/삭제 버튼 출력 구현
>![image](https://github.com/user-attachments/assets/7b156bb9-7eb6-49a9-92a9-d23a63eade79)
>![image](https://github.com/user-attachments/assets/76f56105-e2e9-441f-88cb-62db9582008e)
>
=> [#140] ✨ feat : comment 해당 작성자만 수정/삭제 버튼 출력 구현

src/components/CommentSection.jsx
> #148 
> Close #148 
> ![image](https://github.com/user-attachments/assets/5809b519-44a2-4194-872b-8e412013672d)
> ![image](https://github.com/user-attachments/assets/3a40ed20-ad89-4069-b71d-9c7fbab8e7fb)
>
=> [#148] ✨ feat : comment 수정 시간 표기 구현

src/App.js, src/components/Manage/QuestionSettings.jsx, src/pages/ManageCreatePage.jsx, src/pages/ManageMainPage.jsx
> #147 
> Close #147 
> - 관리자 문제 생성 페이지 API 연동
>
=> [#147] ✨ feat : 관리자 문제 생성 페이지 API 연동

src/App.js, src/components/Modal.jsx, src/components/MyPage/MyRoom.jsx, src/components/MyPage/UserInfo.jsx, src/components/SpaceCard.jsx, src/pages/MyPage.jsx, src/pages/MyRoomPage.jsx, src/styles/MyComments.module.css, src/styles/SolvedAnswers.module.css, src/util/AuthContext.js, src/util/useAuth.js
> #114
> Close #114
> ![image](https://github.com/user-attachments/assets/844c0da7-1bbc-4803-9bcc-ffbd4993d8c5)
>
=> [#114] ✨ feat : 특정 사용자가 참여중인 방 목록 api 연동

src/App.js, src/components/Modal.jsx, src/components/MyPage/MyRoom.jsx, src/components/MyPage/UserInfo.jsx, src/components/RoomMain.jsx, src/components/SpaceCard.jsx, src/pages/MyPage.jsx, src/pages/MyRoomPage.jsx, src/styles/MyComments.module.css, src/styles/SolvedAnswers.module.css, src/util/AuthContext.js, src/util/useAuth.js
> #153
> Close #153
> ![image](https://github.com/user-attachments/assets/b85f8aa8-9dc2-4f04-9086-d1df9bd50f66)
>
=> [#153] 🩹 fix : 문제 제목 검색 기능

public/index.html, src/components/ManageMainHeaderNav.jsx
> #160
> Close #160
> - navigate 설정
>
=> [#160] 🩹 fix : 관리자페이지 문제목록 navigate 설정

src/components/ManageMainHeaderNav.jsx, src/components/RoomMain.jsx, src/pages/ManageMainPage.jsx, src/pages/ManageReadPage.jsx
> #156 
> Close #156 
> - 관리자 문제목록 버튼 구현 완료
>![image](https://github.com/user-attachments/assets/60b9b19d-f69d-4a12-bbfc-34aeb096539e)
>![image](https://github.com/user-attachments/assets/676f65fa-ebe1-4f8d-bcee-cb799840b347)
>
=> [#156] ✨ feat : roommain, magemain 문제번호 새로 추가 부여 구현 완료

src/components/ManageMainHeaderNav.jsx, src/pages/ManageMainPage.jsx
> #166 
> Close #166 
> ![image](https://github.com/user-attachments/assets/da6896c4-f81d-4e0a-b55a-7d8be3bc9051)
>
=> [#166] 🩹 fix : managemainpage 코드 중복 수정

src/components/HeaderNavComponent.jsx, src/components/ManageMainHeaderNav.jsx, src/components/RoomLayout.jsx, src/pages/ManageMainPage.jsx, src/styles/HeaderNavComponent.module.css, src/styles/ManageMainHeaderNav.module.css
> #168 
> Close #168
> - 방 설정에 따라 HeaderNavBar private, public 헤더바 표시 구현
>![image](https://github.com/user-attachments/assets/3ce56798-8282-4cff-a0fb-0a52eae26d27)
>![image](https://github.com/user-attachments/assets/43f040fa-630a-4dbc-b994-8681df76d21c)
>
=> [#168] ✨feat: 방 관련 코드 수정

src/pages/ManageMainPage.jsx
> #163 
> Close #163 
> ![image](https://github.com/user-attachments/assets/a6489851-5a60-4c61-8ca2-060f2c5970eb)
> ![image](https://github.com/user-attachments/assets/7b286b5d-fa24-4487-aa90-443fbbff132a)
>
=> [#163] ✨ feat : 관리자 메인 페이지 출제일 조회 기능 구현

src/components/ManageMainHeaderNav.jsx
> #171 
> Close #171 
> - 관리자 문제 수정 기능 코드 수정
>
=> [#171] 🩹 fix : 관리자 문제 수정 기능 코드 수정

src/components/HeaderNavComponent.jsx, src/components/ManageMainHeaderNav.jsx, src/components/RoomLayout.jsx, src/pages/ManageMainPage.jsx, src/styles/ManageMainHeaderNav.module.css
> #173 
>#161
> Close #173 
> Close #161 
> ![image](https://github.com/user-attachments/assets/f1588476-462d-4533-a50e-f986efb9fae0)
>![image](https://github.com/user-attachments/assets/5e3ff0cc-eab5-41f1-986b-a6a7cbbfb0dd)
>
=> [#173, #161] 🩹 fix : 백엔드 수정으로 인한 프론트 관리자 관련 수정, 난이도 정렬 추가 구현

src/components/SidebarComponent.jsx
> #175 
> Close #175 
> - 관리자페이지에서 사이드바 상단 RoomName을 누르면 룸 조회화면으로 이동 구현
>
=> [#175] ✨ feat : 관리자페이지에서 사이드바 상단 RoomName을 누르면 룸 조회화면으로 이동 구현

src/components/ManageMainHeaderNav.jsx, src/pages/ManageCreatePage.jsx, src/pages/ManageModifyPage.jsx, src/pages/ManageReadPage.jsx
> #178 
> Close #178 
> - 관리자 페이지 문제 조회, 생성, 수정 시 해당 방 표시 오류
>![image](https://github.com/user-attachments/assets/d86e7aaa-7e4f-478a-9d02-ce3b5e39f4bc)
>![image](https://github.com/user-attachments/assets/cd7a8755-5fcc-4b42-b47c-cc48bd1d83af)
>![image](https://github.com/user-attachments/assets/95b3be0c-8eab-4d06-9ccb-af2bd11470b9)
>
=> [#178] 🩹 fix : 관리자 페이지 문제 조회, 생성, 수정 시 해당 방 표시 오류

src/components/MyPage/MyComments.jsx, src/components/MyPage/SolvedAnswers.jsx, src/components/MyPage/WrongAnswers.jsx, src/components/RoomMain.jsx, src/pages/ManageMainPage.jsx, src/styles/ManageMainHeaderNav.module.css
> #184
> Close #184
> ![image](https://github.com/user-attachments/assets/cfa24694-df61-4d02-9afe-d0f48f692fd6)
> ![image](https://github.com/user-attachments/assets/474f2476-1242-48eb-a0a7-4cbf4e9c9eee)
> ![image](https://github.com/user-attachments/assets/2b848a51-b656-48ef-8176-f01ad5316769)
>
=> [#184] 🩹 fix : Room마다 독립적 QuestionId 부여 및 프론트 코드 수정

src/pages/ManageReadPage.jsx
> #188
> Close #188
> - solvedStudents 상태 빈 배열 []로 초기화
>
=> [#188] 🩹 관리자 조회페이지도 이동 안되는 문제 수정

src/pages/ManageMainPage.jsx, src/styles/ManageMainPage.module.css
> #190 
> Close #190 
>![image](https://github.com/user-attachments/assets/c438e217-9e00-4a66-b8ae-4f1a996e0767)
>
=> [#190] ✨ feat : 관리자 페이지 수정일 추가

src/App.js, src/components/SpaceCard.jsx, src/styles/Header.module.css, src/styles/HeaderNavComponent.module.css, src/styles/ManageMainHeaderNav.module.css, src/styles/MyPage.module.css, src/styles/SpaceCard.module.css
> #192
> Close #192
> ![image](https://github.com/user-attachments/assets/fbc9df34-545a-4725-ba09-32fcd0ac242e)
>
=> [#192] ✨ feat : 룸 메인페이지 방 이름 검색창

src/components/ChatWidget.jsx, src/components/CommentSection.jsx, src/components/ForgotPassword.jsx, src/components/Login.jsx, src/components/Manage/ManageMainHeaderNav.jsx, src/components/Modal.jsx, src/components/MyPage/ChangePassword.jsx, src/components/MyPage/MyRoom.jsx, src/components/MyPage/UserInfo.jsx, src/components/QuestionDetail.jsx, src/components/RoomLayout.jsx, src/components/RoomMain.jsx, src/components/SidebarComponent.jsx, src/components/Signup.jsx, src/components/SpaceCard.jsx, src/pages/ManageCreatePage.jsx, src/pages/ManageMainPage.jsx, src/pages/ManageModifyPage.jsx, src/pages/ManageReadPage.jsx, src/pages/MyPage.jsx, src/pages/QuestionDetailPage.jsx, src/util/AuthContext.js
> #194
> Close #194
> - 모든 파일 백엔드 api path 수정
>
=> [#194] 🩹fix : 모든 파일 백엔드 api path 수정

src/App.js, src/components/Header.jsx, src/pages/KakaoRedirect.jsx, src/pages/ManageReadPage.jsx, src/util/AuthContext.js, src/util/axiosConfig.js
> #196 
> Close #196 
> - 카카오 로그인 기능 수정
>
=> [#196] 🩹 fix : 카카오 로그인 기능 수정

src/components/ChatWidget.jsx, src/components/Modal.jsx, src/components/MyPage/UserInfo.jsx, src/components/SpaceCard.jsx, src/styles/SpaceCard.module.css
> #198
> Close #198
> - 방 참여 인원수
> - 방 검색창 위치 변경
> - 모달창 css 수정
>
=> [#198] ✨ feat : 인원수 api 연동

src/components/MyPage/UserInfo.jsx, src/pages/MyPage.jsx
> #200
> Close #200
> - 마이페이지 프로필 편집 기능 구현
>
=> [#200] ✨ feat : 프로필 편집 이미지 업로드 api 연동

src/components/Header.jsx, src/components/MyPage/UserInfo.jsx, src/components/Signup.jsx, src/pages/MyPage.jsx, src/styles/MyPage.module.css
> #203 
> Close #203 
> - 회원가입 닉네임 중복 확인, 닉네임 변경 중복 확인, 회원탈퇴 기능 구현
>
=> [#203] ✨ feat : 회원가입 닉네임 중복 확인, 닉네임 변경 중복 확인, 회원탈퇴 기능 구현

src/components/HeaderNavComponent.jsx, src/components/MyPage/UserInfo.jsx, src/components/QuestionDetail.jsx, src/styles/Header.module.css, src/styles/HeaderNavComponent.module.css, src/styles/HomePage.module.css, src/styles/ManageMainHeaderNav.module.css, src/styles/ManageMainPage.module.css, src/styles/MyComments.module.css, src/styles/MyPage.module.css, src/styles/QuestionDetail.module.css, src/styles/RoomMainPage.module.css, src/styles/SpaceCard.module.css, src/styles/UserInfo.module.css
> #202
> Close #202
> ![image](https://github.com/user-attachments/assets/e501bfb2-88c7-4eb7-9803-1cdef5ba9dac)
>
=> [#202] 💄 style : 전체적인 CSS 통일

src/components/MyPage/UserInfo.jsx
> #206
> Close #206
> - 프로필 사진 수정 버튼에서만 파일 선택 창 뜨도록 수정
>
=> [#206] 🐛 bugfix : 파일 선택 창 버그 수정

src/components/MyPage/MyRoom.jsx
> #208
> Close #208
> - 마이룸 인원수 api 연동
>
=> [#208] ✨ feat : 마이룸 인원수 api 연동

src/components/ChatWidget.jsx, src/components/CommentSection.jsx, src/components/HeaderNavComponent.jsx, src/components/Login.jsx, src/components/Manage/ManageMainHeaderNav.jsx, src/components/Modal.jsx, src/components/MyPage/ChangePassword.jsx, src/components/QuestionDetail.jsx, src/components/RoomLayout.jsx, src/components/RoomMain.jsx, src/components/SidebarComponent.jsx, src/pages/ManageCreatePage.jsx, src/pages/ManageMainPage.jsx, src/pages/ManageModifyPage.jsx, src/pages/ManageReadPage.jsx, src/pages/MyPage.jsx, src/util/AuthContext.js
> #212 
> Close #212 
> - 유저페이지 문제번호 최신순으로 수정 및 불필요한 콘솔로그 제거
> -
>
=> [#212] 🩹 fix : 유저페이지 문제번호 최신순으로 수정 및 불필요한 콘솔로그 제거

src/pages/ManageCreatePage.jsx
> #216 
> Close #216 
> - 문제 생성 시 빈칸 있으면 문제 생성 불가능하게 수정
>
=> [#216] 🩹 fix : 문제 생성 시 빈칸 있으면 문제 생성 불가능하게 수정

src/components/Modal.jsx, src/styles/SpaceCard.module.css
> #215
> Close #215
> - ![image](https://github.com/user-attachments/assets/4d3f0de0-de2b-4ec4-a05c-f8be6a03fca3)
> - ![image](https://github.com/user-attachments/assets/1357f4e9-aecc-4f12-ab3b-004264153011)
> - public, private 버튼 클릭 hover 추가
>
=> [#215] 🩹 fix : public, private 버튼 클릭 hover 추가

package-lock.json, package.json, src/components/HeaderNavComponent.jsx, src/styles/AIQuestionModal.module.css, src/util/AIQuestionModal.js
> #219 
> Close #219 
> - Gemini 추가 기능 구현
> -
>
=> [#219] ✨ feat : Gemini 추가 기능 구현

package.json
> #xxxxx
> Close #xxxxx
> - (스크린샷 선택)
> - package.json CI 추가
>
=> fix : package.json CI 추가

src/components/MyPage/ChangePassword.jsx
> #214 
> Close #214
> - 비밀번호 변경 정규식 수정
>
=> [#214] 🩹 fix : 비밀번호 정규식 수정

src/components/SpaceCard.jsx, src/styles/SpaceCard.module.css
> #223 
> Close #223 
> - ![image](https://github.com/user-attachments/assets/6c78207a-132c-43af-96e9-ddd461b1d081)
> -메인페이지 방 페이징 처리
>
=> [#223] 🩹 fix : 메인페이지 방 페이징 처리

src/components/MyPage/UserInfo.jsx, src/styles/UserInfo.module.css
> #222
> Close #222
> ![image](https://github.com/user-attachments/assets/78d21a2f-1536-4443-97a1-c82b053c06ae)
>
=> [#222] ✨ feat : 랭크 설명 기능 추가
